/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#40474f',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        outline: '#707881',
        'outline-variant': '#c0c7d1',
        'surface-tint': '#006399',
        primary: '#00507d',
        'on-primary': '#ffffff',
        'primary-container': '#0369a1',
        'on-primary-container': '#cbe4ff',
        'inverse-primary': '#94ccff',
        secondary: '#006d30',
        'on-secondary': '#ffffff',
        'secondary-container': '#92f5a4',
        'on-secondary-container': '#007233',
        tertiary: '#733f00',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#955301',
        'on-tertiary-container': '#ffdbbe',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#cde5ff',
        'primary-fixed-dim': '#94ccff',
        'on-primary-fixed': '#001d32',
        'on-primary-fixed-variant': '#004b74',
        background: '#f8f9ff',
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
      },
      spacing: {
        xs: '4px',
        sm: '8px',
        md: '16px',
        lg: '24px',
        xl: '32px',
        gutter: '24px',
        'sidebar-width': '280px',
        'container-max': '1440px',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
        display: ['Lexend', 'Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['48px', { lineHeight: '56px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}
